version: '3'
services:
  nodejs-backend:
    build:
      context: .docker/nodejs
    volumes:
      - ./:/var/www/ideas
    working_dir: /var/www/ideas
    tty: true
    ports:
      - "3000:3000"
    environment:
      - npm_config_unsafe_perm=true
      #allow hot reload on docker volumes
      - CHOKIDAR_USEPOLLING=true
      #decrease CPU load
      - CHOKIDAR_INTERVAL=1000
      - CHOKIDAR_USE_FS_EVENTS=true
      - CHOKIDAR_IGNORE_PERMISSION_ERRORS=true
  postgres-backend:
    build:
      context: .docker/postgres
    restart: always
    ports:
      # care, custom port for prevent conflict
      - "5433:5432"
#    volumes:
#      - .docker/postgres/dbfiles:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_PASSWORD}
      # PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: "--pgdata=/var/lib/postgresql/data/pgdata"
